apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: control-plane-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - control-plane-pool
  namespaceSelectors:
    - matchLabels:
        name: metallb-system

