apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info        # valid
  reportingInterval: 0s          # valid, disable usage reporting
  failsafeOutboundHostPorts:
    - protocol: TCP
      port: 22
    - protocol: TCP
      port: 179
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 5473
