apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
  namespace: tigera-operator
spec:
  variant: Calico
  calicoNetwork:
    bgp: Disabled
     
  cni:
    type: Calico
    ipam:
      type: Calico
  controlPlaneReplicas: 1   # because you're no longer scheduling on control-plane
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
