apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.x.x
    helm:
      valueFiles:
        - ../../../../apps/business/store-api/values.yaml
  destination:
    namespace: business
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

