# Core Infrastructure Namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    argocd.argoproj.io/instance: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong
  labels:
    name: kong
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    name: rook-ceph
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
  labels:
    name: cloudflared
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    name: external-secrets-system
---
# Application Namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: business
  labels:
    name: business
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default

