# Ceph Storage Node Labels and Taints
# Apply these to nodes dedicated to Ceph storage

apiVersion: v1
kind: Node
metadata:
  name: ceph-01
  labels:
    node.ceph.storage: "true"
    node.role: "storage"
spec:
  taints:
    - key: node.ceph.storage
      value: "true"
      effect: NoSchedule
---
apiVersion: v1
kind: Node
metadata:
  name: ceph-02
  labels:
    node.ceph.storage: "true"
    node.role: "storage"
spec:
  taints:
    - key: node.ceph.storage
      value: "true"
      effect: NoSchedule
---
apiVersion: v1
kind: Node
metadata:
  name: ceph-03
  labels:
    node.ceph.storage: "true"
    node.role: "storage"
spec:
  taints:
    - key: node.ceph.storage
      value: "true"
      effect: NoSchedule

