# Worker Node Labels
# Apply these to general worker nodes

apiVersion: v1
kind: Node
metadata:
  name: worker-01
  labels:
    node.role: "worker"
    node.type: "compute"
spec: {}
---
apiVersion: v1
kind: Node
metadata:
  name: worker-02
  labels:
    node.role: "worker"
    node.type: "compute"
spec: {}
---
apiVersion: v1
kind: Node
metadata:
  name: worker-03
  labels:
    node.role: "worker"
    node.type: "compute"
spec: {}

