apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: {{ .Values.cephCluster.cephVersion.image }}
    allowUnsupported: {{ .Values.cephCluster.cephVersion.allowUnsupported | default false }}
  dataDirHostPath: {{ .Values.cephCluster.dataDirHostPath }}
  mon:
    count: {{ .Values.cephCluster.mon.count }}
    allowMultiplePerNode: {{ .Values.cephCluster.mon.allowMultiplePerNode }}
    {{- if .Values.cephCluster.mon.nodes }}
    nodes:
      {{- toYaml .Values.cephCluster.mon.nodes | nindent 6 }}
    {{- end }}
  {{- if .Values.cephCluster.mgr }}
  mgr:
    {{- toYaml .Values.cephCluster.mgr | nindent 4 }}
  {{- end }}
  {{- if .Values.cephCluster.rbdMirroring }}
  rbdMirroring:
    {{- toYaml .Values.cephCluster.rbdMirroring | nindent 4 }}
  {{- end }}
  {{- if .Values.cephCluster.config }}
  config:
    {{- toYaml .Values.cephCluster.config | nindent 4 }}
  {{- end }}
  network:
    provider: {{ .Values.cephCluster.network.provider }}
    {{- if .Values.cephCluster.network.selectors }}
    selectors:
      {{- toYaml .Values.cephCluster.network.selectors | nindent 6 }}
    {{- end }}
  storage:
    useAllNodes: {{ .Values.cephCluster.storage.useAllNodes }}
    useAllDevices: {{ .Values.cephCluster.storage.useAllDevices }}
    nodes:
      {{- toYaml .Values.cephCluster.storage.nodes | nindent 6 }}
    config:
      {{- toYaml .Values.cephCluster.storage.config | nindent 6 }}
  resources:
    {{- toYaml .Values.cephCluster.resources | nindent 4 }}
  placement:
    {{- toYaml .Values.cephCluster.placement | nindent 4 }}

