apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: {{ .Values.cephCluster.cephVersion.image }}
    allowUnsupported: {{ .Values.cephCluster.cephVersion.allowUnsupported | default false }}
  dataDirHostPath: {{ .Values.cephCluster.dataDirHostPath }}
  mon:
    count: {{ .Values.cephCluster.mon.count }}
    allowMultiplePerNode: {{ .Values.cephCluster.mon.allowMultiplePerNode }}
  network:
    provider: {{ .Values.cephCluster.network.provider }}
  storage:
    useAllNodes: {{ .Values.cephCluster.storage.useAllNodes }}
    useAllDevices: {{ .Values.cephCluster.storage.useAllDevices }}
    nodes:
      {{- toYaml .Values.cephCluster.storage.nodes | nindent 6 }}
    config:
      {{- toYaml .Values.cephCluster.storage.config | nindent 6 }}
  resources:
    {{- toYaml .Values.cephCluster.resources | nindent 4 }}
  placement:
    {{- toYaml .Values.cephCluster.placement | nindent 4 }}

