apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Murtadah-1984/k8sgitops.git
    targetRevision: main
    path: infra/calico
  destination:
    server: https://kubernetes.default.svc
    namespace: calico-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations     # prevents size explosion again
  syncPolicy:
    automated: null    # ❗ disables background auto-sync
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

