apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://docs.tigera.io/calico/charts"
      chart: tigera-operator
      targetRevision: v3.28.1
      helm:
        valueFiles:
          - $values/infra/calico/values.yaml
    - repoURL: https://github.com/Murtadah-1984/k8sgitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: calico-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

