apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR/repo.git
    targetRevision: main
    path: infra/ceph
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

