apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: v1.14.x
    helm:
      valueFiles:
        - ../../../infra/ceph/rook-values.yaml
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

