apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://charts.bitnami.com/bitnami"
      chart: kong
      targetRevision: "15.4.22"
      helm:
        valueFiles:
          - $values/infra/kong/values.yaml
    - repoURL: https://github.com/Murtadah-1984/k8sgitops.git
      targetRevision: main
      ref: values
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
