apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/mysql/mysql-operator
      targetRevision: 8.0.36-2.0.12
      path: deploy/charts/mysql-operator
      helm:
        valueFiles:
          - $values/infra/mysql-operator/values.yaml
    - repoURL: https://github.com/Murtadah-1984/k8sgitops.git
      targetRevision: main
      ref: values
  destination:
    namespace: mysql-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

