apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keepalived-cp1
  namespace: keepalived
  labels:
    app: keepalived
    node: cp1
spec:
  selector:
    matchLabels:
      app: keepalived
      node: cp1
  template:
    metadata:
      labels:
        app: keepalived
        node: cp1
    spec:
      serviceAccountName: keepalived
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-cp-01
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: keepalived
        image: osixia/keepalived:2.0.20
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN","NET_BROADCAST","NET_RAW","SYS_TIME"]
        command: ["keepalived"]
        args:
          - "--dont-fork"
          - "--log-console"
          - "--config"
          - "/etc/keepalived/keepalived.conf"
        volumeMounts:
          - name: config
            mountPath: /etc/keepalived/keepalived.conf
            subPath: keepalived.conf
        livenessProbe:
          exec:
            command: ["pgrep","keepalived"]
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pgrep","keepalived"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: keepalived-config-cp1

