apiVersion: v1
kind: Namespace
metadata:
  name: keepalived
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keepalived
  namespace: keepalived
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: keepalived
  labels:
    app: keepalived
spec:
  selector:
    matchLabels:
      app: keepalived
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      serviceAccountName: keepalived
      hostNetwork: true                      # Pod sees host NICs directly
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""   # Run only on control-plane nodes
      tolerations:         # 🔥 THIS SECTION WAS MISSING
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
      containers:
      - name: keepalived
        image: osixia/keepalived:2.0.20
        securityContext:
          privileged: true                    # Required for VRRP + ARP
          capabilities:
            add:
              - NET_ADMIN
              - NET_BROADCAST
              - NET_RAW
              - SYS_TIME
        env:
        - name: KEEPALIVED_INTERFACE
          value: "eno1.20"                    # 🔁 Your VLAN 20 interface
        - name: KEEPALIVED_VIRTUAL_IPS
          value: "10.0.20.10/24"              # 🔁 Your Control Plane VIP
        - name: KEEPALIVED_ROUTER_ID
          value: "LVS_KUBERNETES"
        - name: KEEPALIVED_PASSWORD
          value: "CP_VipSecret"
        - name: KEEPALIVED_VIRTUAL_ROUTER_ID
          value: "51"
        - name: KEEPALIVED_PRIORITY
          value: "100"                        # Same on all nodes; highest IP wins
        livenessProbe:
          exec:
            command: ["pgrep","keepalived"]
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pgrep","keepalived"]
          initialDelaySeconds: 5
          periodSeconds: 5

