apiVersion: v1
kind: Namespace
metadata:
  name: keepalived
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keepalived
  namespace: keepalived
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-config
  namespace: keepalived
data:
  keepalived.conf: |
    global_defs {
      router_id LVS_KUBERNETES
    }

    vrrp_instance VI_CONTROL_PLANE {
      state MASTER
      interface eno1
      virtual_router_id 51
      priority 100
      advert_int 1
      authentication {
        auth_type PASS
        auth_pass CP_VipSecret
      }
      virtual_ipaddress {
        10.0.20.10/24
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: keepalived
  labels:
    app: keepalived
spec:
  selector:
    matchLabels:
      app: keepalived
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      serviceAccountName: keepalived
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: keepalived
        image: osixia/keepalived:2.0.20
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN","NET_BROADCAST","NET_RAW","SYS_TIME"]
        command: ["keepalived"]        # <--- run real keepalived
        args:
          - "--dont-fork"              # foreground (instead of daemon)
          - "--log-console"
          - "--config"
          - "/etc/keepalived/keepalived.conf"
        volumeMounts:
          - name: config
            mountPath: /etc/keepalived/keepalived.conf
            subPath: keepalived.conf
        livenessProbe:
          exec:
            command: ["pgrep","keepalived"]
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pgrep","keepalived"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: keepalived-config
